### PR TITLE
fixes issues with async

### LINKED ISSUE #36: issues with async 2.0
`filter, reject, some, every, and related functions now expect an error as the first callback argument, rather than just a simple boolean. Pass null as the first argument, or use fs.access instead of fs.exists. (#118, #774, #1028, #1041)`

causes 

```
/root/node-distribute/node_modules/git-server/host.js:269
          if (results.length > 0) {
                     ^
TypeError: Cannot read property 'length' of null
```

### PR DESCRIPTION
**Pull request by gabrielcsapo**
adds async version to package.json

fixes #36

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@stackdot is anyone maintaining this repo?

**Comment by qrpike** [comment]
Not actively, no

**Comment by gabrielcsapo** [comment]
@qrpike would you be interested in moving this under someone who would be actively managing issues?

**Comment by qrpike** [comment]
I would be willing to add you as a contributor if you like, giving you commit access.

**Comment by gabrielcsapo** [comment]
@qrpike that would be great, could you provide NPM access as well?

**Comment by gabrielcsapo** [comment]
@qrpike +1

**Comment by qrpike** [comment]
@gabrielcsapo seems you cant add access to a user npm module now, you have to create a npm org which costs $15/m. I guess just ping me when you need it pushed and I will push it for you. Would be even better if we could get the CI working again and have it auto publish through that only on successful changes.

**Comment by gabrielcsapo** [comment]
@qrpike https://github.com/stackdot/NodeJS-Git-Server/pull/40 this fixes the CI issue.

**Pull request merged**
